orange_book:
  zip_url: "https://www.fda.gov/media/76860/download?attachment"
  zip_file_name: products.txt

FEARS:
  url: "https://api.fda.gov/drug/event.json"
  count: patient.drug.drugcharacterization

NADAC:
  url: "https://data.medicaid.gov/api/1/metastore/schemas/dataset/items/4a00010a-132b-4e4d-a611-543c9521280f?show-reference-ids=ture"